<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Dates   Event 25-Oct-18 05</name>
   <tag></tag>
   <elementGuidId>9f03ef59-7386-4473-9e56-23580d84e0f5</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-body</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectdateinfobody</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   Dates    Event    25-Oct-18 05:30 PM Halloween 5K - Pecan Grove Park    05-Dec-18 05:30 PM Jingle Bell 5K - Community Park    17-Jan-19 07:30 AM Resolutions 5K - Community Park    07-Feb-19 05:30 PM Cupid 5K - Community Park    15-Mar-19 07:30 AM St. Paddy's Day 5K - Community Park    24-May-19 05:30 PM Memorial Day 5K - Community Park    27-Jun-19 07:30 AM Firecracker 5K - Community Park    09-Aug-19 07:30 AM Inferno 5K - Community Park    N/A External 5K    N/A External 5K    N/A External 5K    N/A External 5K    N/A External 5K    N/A External 5K    N/A External 5K    N/A External 5K</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectdateinfobody&quot;)</value>
   </webElementProperties>
</WebElementEntity>
